services:
  db:
    image: bitnami/postgresql:latest
    container_name: sheet-ledger-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    networks:
      - sheet-ledger-network
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: sheet-ledger-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - sheet-ledger-network
  redis:
    image: redis:latest
    container_name: sheet-ledger-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - sheet-ledger-network
networks:
  sheet-ledger-network:
    driver: bridge
