name: Node.js CD


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - run: cd ${{ secrets.SSH_PATH }}
      - run: git pull --rebase

      - run: npm ci
      - run: npm run build
      - run: pm2 start build/server.js --name "sheet-manager-api"