name: Node.js CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Get SSH Key and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy to server
        run: |
          rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env' \
          -e "ssh -i ~/.ssh/id_rsa" \
          . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}

      - name: Connect to server
        run: ssh -i "~/.ssh/id_rsa" ubuntu@${{ secrets.SSH_HOST }}

      - run: npm ci
      - run: npm run build
      - run: npm run start