name: Node.js CD

on:
  push:
    branches:
      - main
env:
  env_var: ${{ github.ref_name }}

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env file
        run: |
          echo '${{ toJSON(vars) }}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > .env

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Stop existing process
        run: pm2 delete "sheet-manager-api" || true

      - name: Check and install PM2
        run: |
          if ! command -v pm2 &> /dev/null; then
            npm i -g pm2
          fi

      - name: Start application
        run: pm2 start build/server.js --name "sheet-manager-api" --update-env