name: Run E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:16
        env:
          POSTGRES_USER: test-docker-user
          POSTGRES_PASSWORD: test-docker-password
          POSTGRESQL_DATABASE: sheet-manager

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Node Setup
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Run E2E Tests
      run: npm run test:e2e
      env:
        JWT_SECRET: testing
        DATABASE_URL: postgresql://test-docker-user:test-docker-password@localhost:5432/sheet-manager
