name: Run Unit Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Node Setup
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Run Unit Tests
      run: npm run test
